CREATE DATABASE IF NOT EXISTS TASK_MANAGER;

USE TASK_MANAGER;

CREATE TABLE IF NOT EXISTS USER(
ID CHAR(8) PRIMARY KEY,
EMAIL VARCHAR(75) NOT NULL UNIQUE,
PASSWORD VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS TASK(
ID INT AUTO_INCREMENT PRIMARY KEY,
TITLE VARCHAR(100) NOT NULL,
CATEGORY VARCHAR(5) NOT NULL,
DESCRIPTION TEXT,
PRIORITY VARCHAR(20) NOT NULL,
DUE_DATE DATE NOT NULL,
COLOR VARCHAR(20) NOT NULL,
USER_ID CHAR(8) NOT NULL,
FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);